app:
    resource: '@AppBundle/Controller/'
    type: annotation

page:
    path: /site/{pageName}/
    defaults:
        _controller: 'AppBundle:Default:page'
    requirements:
        nombrePagina: help|privacity|about-us